version: '3'
services:
  next:
    container_name: amplify-test-2
    build:
      context: .
      dockerfile: ./docker/development/next/Dockerfile
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    ports:
      - '3001:3000'
    tty: true

volumes:
  node_modules_volume:
