FROM node:19.2.0-slim
RUN apt-get update && apt -y install git python python3-pip make g++

RUN mkdir -p /app
WORKDIR /app
#COPY /package.json /app/package.json
#COPY /package-lock.json /app/package-lock.json
#RUN npm install
